name: Build Plugin

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  PLUGIN_NAME: Lidarr.Plugin.UniqueSingles
  PLUGIN_VERSION: 1.0.2.${{ github.run_number }}
  DOTNET_VERSION: 8.0.405

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        run: |
          dotnet restore UniqueSingles.sln /p:WarningsNotAsErrors="NU1902"
          dotnet build UniqueSingles.sln -c Release /p:WarningsNotAsErrors="NU1902"

      - name: Test
        run: |
          dotnet test tests/UniqueSingles.Test/UniqueSingles.Test.csproj -c Release --no-build --verbosity normal

      - name: Zip Plugin
        if: github.ref == 'refs/heads/main'
        run: |
          cd _temp/bin/Release/UniqueSingles
          zip /tmp/${{ env.PLUGIN_NAME }}.net8.0.zip Lidarr.Plugin.UniqueSingles.dll Lidarr.Plugin.UniqueSingles.pdb

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: ${{ env.PLUGIN_VERSION }}
          name: ${{ env.PLUGIN_VERSION }}
          draft: true
          files: /tmp/${{ env.PLUGIN_NAME }}.net8.0.zip
